name: ServerSystem
version: A1.0
author: PixelTeleV

main: ch.PixelTV.Main.Main

commands:
  fly:
  gm:
    aliases: [gamemode]
  tpa:
  tpaccept:
  tpdeny:
  spawn:
  enderchest:
    aliases: [ec]
  workbench:
    aliases: [wb]