name: ServerSystem
version: A1.0
author: PixelTeleV

main: ch.pixeltv.main.main

commands:
  fly:
  gm:
    aliases: [gamemode]
  spawn:
  enderchest:
    aliases: [ec]
  workbench:
    aliases: [wb]
  tpa:
  tpaccept:
  tpdeny:
  suicide:
  invsee:
  msg:
  skull: